### ISSUE TITLE
move tm to homebrew-core 

### ISSUE THREAD

**Issue by sameersbn** [triggermesh/homebrew-tap#1]

**Comment by antoineco** [comment]
I doubt it will be accepted.

**Comment by sameersbn** [comment]
why do you think that? I have contributed another package to the library in the past and faced no pushback whatsoever.

**Comment by antoineco** [comment]
Updated my comment just now. I got packages rejected in the past, but you can try and see.

**Comment by sameersbn** [comment]
hmm.. may get rejected because of the `usage` criteria. I'll give it a try anyway

**Comment by sameersbn** [comment]
https://github.com/Homebrew/homebrew-core/pull/65699

**Comment by sameersbn** [comment]
well like you expected, the homebrew ci fails with the following error ` * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)`

**Comment by sameersbn** [comment]
hahaha.. turns out they need one of those criteria to be met. tm reached the 75 star count after I starred it :stuck_out_tongue:

**Comment by sameersbn** [comment]
https://github.com/Homebrew/homebrew-core/commit/bb20a907fa7baa2540e27b4d997013a27ac272c8
